from __future__ import annotations

import argparse
import logging
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Iterable

from .blend import blend_static_instance
from .detect import describe_source, detect_source
from .instance import materialize_instance, plan_static_outputs
from .naming import default_blend_family
from .progress import ProgressReporter
from .tui import TuiCancelled, run_tui


def main(argv: list[str] | None = None) -> int:
    _quiet_fonttools_logs()
    parser = _parser()
    args = parser.parse_args(argv)
    interactive = args.tui

    if interactive:
        try:
            args = run_tui(args)
        except TuiCancelled:
            print("FontMerger: cancelled")
            return 130
        args.tui = False

    if not args.primary or not args.secondary:
        parser.error("--primary and --secondary are required unless --tui provides them")

    args.primary = _clean_path_text(args.primary)
    args.secondary = _clean_path_text(args.secondary)
    args.out_dir = _clean_path_text(args.out_dir)
    if args.tmp_dir:
        args.tmp_dir = _clean_path_text(args.tmp_dir)

    primary = detect_source(Path(args.primary))
    secondary = detect_source(Path(args.secondary))

    print(f"Primary:   {describe_source(primary)}")
    print(f"Secondary: {describe_source(secondary)}")

    default_name = default_blend_family(primary.faces[0], secondary.faces[0])

    family_name = (args.family_name or default_name).strip()
    print(f"Family:    {family_name}")

    out_dir = Path(args.out_dir).expanduser().resolve()
    tmp_root = Path(args.tmp_dir).expanduser().resolve() if args.tmp_dir else Path(tempfile.mkdtemp(prefix="FontMerger-"))
    cleanup_tmp = args.tmp_dir is None

    try:
        jobs = plan_static_outputs(primary, secondary, out_dir, args.output, args.instances, family_name)
        generated: list[Path] = []
        print("")
        print(f"Building {len(jobs)} output font(s). Primary glyphs are protected; secondary fills missing Unicode only.")
        with ProgressReporter(total_jobs=len(jobs)) as progress:
            for index, job in enumerate(jobs, start=1):
                progress.start_job(index, f"{job.subfamily} ({job.label})")
                primary_path = materialize_instance(job.primary_face, job.primary_location, tmp_root)
                progress.advance("Primary instance ready")
                secondary_path = materialize_instance(job.secondary_face, job.secondary_location, tmp_root)
                progress.advance("Secondary instance ready")
                output_path, added = blend_static_instance(job, primary_path, secondary_path, progress.advance)
                progress.finish_job(output_path, added)
                generated.append(output_path)

        print("")
        print("Generated files:")
        for path in generated:
            print(f"  {path}")
        return 0
    except Exception as exc:
        print(f"FontMerger: error: {exc}", file=sys.stderr)
        return 1
    finally:
        if cleanup_tmp:
            shutil.rmtree(tmp_root, ignore_errors=True)


def _quiet_fonttools_logs() -> None:
    for name in ("fontTools.merge", "fontTools.subset"):
        logging.getLogger(name).setLevel(logging.ERROR)


def _clean_path_text(value: str) -> str:
    cleaned = " ".join(str(value).replace("\r", "\n").splitlines()).strip()
    if len(cleaned) >= 2 and cleaned[0] == cleaned[-1] and cleaned[0] in {"'", '"'}:
        cleaned = cleaned[1:-1].strip()
    return cleaned


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="FontMerger",
        description="Fallback font merger: preserve Primary and fill only missing glyphs from Secondary.",
    )
    parser.add_argument("--primary", help="Primary font file or family directory")
    parser.add_argument("--secondary", help="Secondary font file or family directory")
    parser.add_argument("--name", "--family-name", dest="family_name", help="Output font family name")
    parser.add_argument("--output", choices=["auto", "static", "variable"], default="auto")
    parser.add_argument("--instances", choices=["auto", "named", "custom"], default="auto")
    parser.add_argument("--synthetic-italic", action="store_true", help="Reserved; synthetic italic is not generated by default")
    parser.add_argument("--out-dir", default="./out")
    parser.add_argument("--tmp-dir")
    parser.add_argument("--tui", action="store_true", help="Prompt for paths and options in a simple terminal UI")
    return parser


def _prompt_paths(args: argparse.Namespace) -> argparse.Namespace:
    _print_step("1", "Choose input fonts")
    args.primary = args.primary or _prompt_text("Primary", "path to primary font or family directory", path=True)
    args.secondary = args.secondary or _prompt_text("Secondary", "path to secondary font or family directory", path=True)
    args.primary = args.primary.strip().strip('"')
    args.secondary = args.secondary.strip().strip('"')
    print("")
    return args


def _prompt_options(args: argparse.Namespace, default_name: str) -> argparse.Namespace:
    print("")
    _print_step("3", "Name and output")
    args.family_name = args.family_name or _prompt_text("Family name", default_name)
    args.output = _prompt_choice("Output", args.output, ["auto", "static", "variable"])
    args.instances = _prompt_choice("Instances", args.instances, ["auto", "named", "custom"])
    args.out_dir = _prompt_text("Out dir", args.out_dir, path=True) or args.out_dir
    return args


def _prompt_choice(label: str, default: str, choices: list[str]) -> str:
    while True:
        value = _prompt_text(label, default, choices=choices) or default
        if value in choices:
            return value
        _print_warning(f"Choose one of: {', '.join(choices)}")


def _prompt_text(
    label: str,
    placeholder: str,
    *,
    path: bool = False,
    choices: Iterable[str] | None = None,
) -> str:
    try:
        from prompt_toolkit import HTML, prompt
        from prompt_toolkit.completion import PathCompleter, WordCompleter
        from prompt_toolkit.formatted_text import HTML as FormattedHTML
        from prompt_toolkit.styles import Style

        completer = None
        if path:
            completer = PathCompleter(expanduser=True)
        elif choices:
            completer = WordCompleter(list(choices), ignore_case=True)

        style = Style.from_dict(
            {
                "prompt": "ansicyan bold",
                "placeholder": "ansibrightblack",
                "toolbar": "ansibrightblack",
            }
        )
        return prompt(
            FormattedHTML(f"<prompt>{_escape_html(label)}</prompt>: "),
            placeholder=HTML(f"<placeholder>{_escape_html(placeholder)}</placeholder>"),
            bottom_toolbar=HTML("<toolbar>Enter accepts the gray default. Type to override.</toolbar>"),
            completer=completer,
            style=style,
        ).strip()
    except Exception:
        return input(f"{label} [{placeholder}]: ").strip()


def _escape_html(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _print_banner() -> None:
    _styled_print("")
    _styled_print("<title>FontMerger</title>")
    _styled_print("<muted>Primary is preserved. Secondary fills only missing Unicode glyphs.</muted>")
    _styled_print("<rule>==============================================================</rule>")
    _styled_print("")


def _print_step(number: str, title: str) -> None:
    _styled_print(f"<accent>[{number}/3]</accent> <heading>{_escape_html(title)}</heading>")


def _print_detected(primary, secondary) -> None:
    _print_step("2", "Detected sources")
    _print_kv("Primary", describe_source(primary))
    _print_kv("Secondary", describe_source(secondary))


def _print_config(args: argparse.Namespace, family_name: str) -> None:
    _styled_print("")
    _styled_print("<heading>Ready to blend</heading>")
    _print_kv("Family", family_name)
    _print_kv("Output", args.output)
    _print_kv("Instances", args.instances)
    _print_kv("Out dir", args.out_dir)
    _styled_print("")


def _print_kv(label: str, value: str) -> None:
    _styled_print(f"  <muted>{_escape_html(label):<10}</muted> {_escape_html(value)}")


def _print_warning(message: str) -> None:
    _styled_print(f"<warning>{_escape_html(message)}</warning>")


def _styled_print(markup: str) -> None:
    try:
        from prompt_toolkit import print_formatted_text
        from prompt_toolkit.formatted_text import HTML
        from prompt_toolkit.styles import Style

        style = Style.from_dict(
            {
                "title": "ansicyan bold",
                "heading": "ansiwhite bold",
                "accent": "ansicyan bold",
                "muted": "ansibrightblack",
                "rule": "ansibrightblack",
                "warning": "ansiyellow",
            }
        )
        print_formatted_text(HTML(markup), style=style)
    except Exception:
        plain = (
            markup.replace("<title>", "")
            .replace("</title>", "")
            .replace("<heading>", "")
            .replace("</heading>", "")
            .replace("<accent>", "")
            .replace("</accent>", "")
            .replace("<muted>", "")
            .replace("</muted>", "")
            .replace("<rule>", "")
            .replace("</rule>", "")
            .replace("<warning>", "")
            .replace("</warning>", "")
        )
        print(plain)
